spring.application.name=networks
spring.datasource.url=jdbc:mysql://localhost:3307/linkedin?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
server.port=8080
jwt.secret.key=d4513e31f8c53d03c7b9c033967199926b7bde119e7dce80148bb449d35e7dcd
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
